### ISSUE TITLE
Getting started for a WP amateur

### ISSUE THREAD

**Issue by begleysm** [bhoot-biswas/easy-digital-downloads-reviews#1]
Hello,

I'm excited about your extension!  I'm in the process of putting together a free community resource website using [Easy Digital Downloads](https://wordpress.org/plugins/easy-digital-downloads/) (and the Rara Themes "[Digital Downloads](https://wordpress.org/themes/digital-download/)" theme).  I really wanted ratings/reviews but my site won't make any money so the $89/year for the official extension is unworkable.  Your extension came around at a perfect time!

Excuse my amateur questions but I'm pretty new to WordPress.  Googling has failed me so far.  Do you have any example code on how to insert your ratings/reviews into a single download page from an existing theme?  It looks like `single-download-reviews.php` is what I likely need to include but I'm having trouble doing so.

Here is my specific setup and what I'm trying.  The Digital Downloads theme creates a page for each download from `single-download.php` (attached).  On line 18 it calls in parts from `template-parts/content-download.php` (attached).  I'd like to insert your reviews between lines 26 & 27 in `content-download.php` but I'm not sure what the call is.
[digital_downloads_files.zip](https://github.com/bhoot-biswas/easy-digital-downloads-reviews/files/4825666/digital_downloads_files.zip)

I've tried variations on `get_template_part( 'reviews-for-easy-digital-downloads/single-download-reviews' );` but I don't think I have the slug right.  I've also tried variations on `include 'reviews-for-easy-digital-downloads/single-download-reviews.php';` but, from what I've read, `include` is not the preferred method for use in WordPress.

Any help would be much appreciated!  I also think some examples would be really helpful in the README.

Thanks!,
Sean

**Comment by bhoot-biswas** [comment]
It's really simple. You can use the following code:

`add_action( 'edd_after_download_content', 'edd_reviews_append_comments', 10 );`

Or you can insert the following function in template files:

`edd_reviews_append_comments();`

Hope it will work.

**Comment by begleysm** [comment]
Hmm, so far no luck... I tried copy/pasting each one of the lines into `content-download.php` between lines 26 & 27 and there is no visible change in the page.

My apologies if I'm missing something basic but I'm not an experience theme/plugin editor.

**Comment by bhoot-biswas** [comment]
Please make sure that you have enabled reviews from the Extention settings page. 

Go to **Downloads => Settings => Extentions => Download Reviews** to update settings.

Then create a new download or bulk update existing downloads.  Reviews will be enabled or disabled based on the settings automatically.

**Comment by begleysm** [comment]
Here are my settings
![image](https://user-images.githubusercontent.com/1275999/85851398-990fd200-b77c-11ea-9978-d64e7b1eff9c.png)




I then created a brandnew download



Here is the "original" code without your code activated & the "original" page without your code activated.  Notice the arrow & "Vigilus Mission Pack"  & black banner at the bottom of the screenshot.
![image](https://user-images.githubusercontent.com/1275999/85852173-10923100-b77e-11ea-82cb-f2da74746b30.png)
![image](https://user-images.githubusercontent.com/1275999/85852543-cc536080-b77e-11ea-90ad-88554bd767a9.png)





Here is the code & output screenshots for `add_action( 'edd_after_download_content', 'edd_reviews_append_comments', 10 );`.  Notice that there appears to be a PHP error as the bottom content of the page is no longer shown.
![image](https://user-images.githubusercontent.com/1275999/85851995-c446f100-b77d-11ea-976d-37f2b1e62c40.png)
![image](https://user-images.githubusercontent.com/1275999/85852044-daed4800-b77d-11ea-8409-b14d50e5b6a4.png)





Here is the code & output screenshots for `edd_reviews_append_comments();`.  Notice that there appears to be a PHP error as the bottom content of the page is no longer shown.
![image](https://user-images.githubusercontent.com/1275999/85851898-95c91600-b77d-11ea-8330-3ec0778d57b4.png)
![image](https://user-images.githubusercontent.com/1275999/85851835-716d3980-b77d-11ea-8842-0bdd0213d5cb.png)





This makes me think that, perhaps the calls are "working" but that something else in the code getting called is unhappy?

**Comment by bhoot-biswas** [comment]
Yeah, maybe something is wrong. Please send an email to me regarding this issue, I will take a look into it.

**Comment by bhoot-biswas** [comment]
I have checked, there has a plugin called **Disable Comments** which is causing the issue. Please disable it or make sure comments are enabled for downloads.

**Comment by begleysm** [comment]
I should have known!  Sorry for having to bring you into it.  I enabled that because posts had comments and the individual checkbox to disable them wasn't working... Thank you for your detailed follow-up & help.

I think it would be a wonderful addition to put `add_action( 'edd_after_download_content', 'edd_reviews_append_comments', 10 );` and `edd_reviews_append_comments();` in the readme along with these instructions:

> Please make sure that you have enabled reviews from the Extention settings page.
> 
> Go to Downloads => Settings => Extentions => Download Reviews to update settings.
> 
> Then create a new download or bulk update existing downloads. Reviews will be enabled or disabled based on the settings automatically.

Especially the part about bulk updating existing downloads.
